# Generated by Django 5.1.6 on 2025-02-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=100)),
                ("part_no", models.CharField(max_length=100)),
                ("process", models.JSONField()),
                ("customer", models.CharField(max_length=40)),
                ("product_family", models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "employee_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="WorkerOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_no", models.IntegerField()),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("onhold", "On Hold"),
                            ("finished", "Finished"),
                        ],
                        max_length=20,
                    ),
                ),
                ("output_data", models.JSONField(default=dict)),
            ],
        ),
    ]
