# Generated by Django 5.1.6 on 2025-02-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkerOut",
            new_name="WorkerOutput",
        ),
    ]
