# Generated by Django 5.1.6 on 2025-03-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_product_process_alter_workeroutput_output_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeCSV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
        ),
        migrations.AddField(
            model_name="workeroutput",
            name="current_process_index",
            field=models.IntegerField(default=0),
        ),
    ]
