# Generated by Django 5.2.12 on 2026-03-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_worker_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=90)),
                ('maker', models.CharField(max_length=20)),
                ('lot_no', models.CharField(max_length=50)),
            ],
        ),
    ]
