# Generated by Django 5.2.12 on 2026-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lot_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
