# Generated by Django 5.2.12 on 2026-03-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_item_lot_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lot_no',
        ),
    ]
