# Generated by Django 5.2.12 on 2026-03-13 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_item_lot_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('customer', 'item')},
        ),
        migrations.RemoveField(
            model_name='item',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='item',
            name='part_name',
        ),
        migrations.CreateModel(
            name='Partname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnames', to='app.item')),
            ],
            options={
                'unique_together': {('item', 'part_name', 'maker')},
            },
        ),
    ]
