# Generated by Django 5.2.12 on 2026-03-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customer_item_item_item_customer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partname',
            unique_together={('item', 'part_name')},
        ),
    ]
