# Generated by Django 5.2.12 on 2026-03-14 01:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customer_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('part_name', models.CharField(max_length=255)),
                ('part_maker', models.CharField(max_length=255)),
                ('lot_no', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('NO_GOOD', 'No Good')], db_index=True, max_length=20, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('qr_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['qr_uuid'], name='app_qrcode_qr_uuid_5ac881_idx'), models.Index(fields=['lot_no'], name='app_qrcode_lot_no_02b424_idx'), models.Index(fields=['item_name', 'part_name'], name='app_qrcode_item_na_3951d2_idx'), models.Index(fields=['status'], name='app_qrcode_status_48b27e_idx')],
            },
        ),
    ]
