# Generated by Django 5.2.12 on 2026-03-14 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='verification_notes',
        ),
    ]
