# Generated by Django 5.2.12 on 2026-03-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_qrcode_verification_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_uuid', models.UUIDField(db_index=True)),
                ('qr_item', models.CharField(max_length=255)),
                ('part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('part_maker', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('user_item', models.CharField(max_length=255)),
                ('user_part', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('GOOD', 'Good'), ('NO_GOOD', 'No Good')], max_length=20)),
                ('result', models.CharField(choices=[('GOOD', 'Good'), ('NO_GOOD', 'No Good')], max_length=20)),
                ('backend_updated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['qr_uuid'], name='app_verific_qr_uuid_3b4424_idx'), models.Index(fields=['timestamp'], name='app_verific_timesta_c59095_idx'), models.Index(fields=['status'], name='app_verific_status_ea89d0_idx'), models.Index(fields=['result'], name='app_verific_result_4e6a94_idx')],
            },
        ),
    ]
