# Generated by Django 5.2.12 on 2026-04-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_verificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationlog',
            name='qr_uuid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
