# Generated by Django 6.0.5 on 2026-05-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_verificationlog_qr_uuid_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_name'], name='app_custome_custome_119473_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item'], name='app_item_item_828e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['customer', 'item'], name='app_item_custome_698c12_idx'),
        ),
        migrations.AddIndex(
            model_name='partname',
            index=models.Index(fields=['part_name'], name='app_partnam_part_na_12cc7e_idx'),
        ),
        migrations.AddIndex(
            model_name='partname',
            index=models.Index(fields=['maker'], name='app_partnam_maker_f875e2_idx'),
        ),
        migrations.AddIndex(
            model_name='partname',
            index=models.Index(fields=['item', 'part_name'], name='app_partnam_item_id_40168d_idx'),
        ),
    ]
